---
title: "Modification of sample size in group sequential clinical trials"
output: html_notebook
---

## setup

Total sample size: N
Number of analysis: K, with K-1 interim analysis

$n_k$: number of subjects obtained between (k-1)-th and k-th analysis
$N_k$: total number of subjects obtained up to the k-th analysis

$t_k = N_k / N$: information fraction at the k-th analysis
$T_k$: two-sample mean test statistics at time $t_k$ 

Conditional power: $CP_L(\triangle) = pr(T_K > C_K | T_L, \triangle)$

>> The critical value $\xi_{1-\alpha/2}$ is the value from a standard normal distribution that the test statistics must exceed in order to show a statistically significant result.

O'Brien-Flemming $\alpha$-spending function

## What would happen to the type I error if, during the study, sample sizes were increased? 

## Simulation

## The intuition: as a result of sample size adjustment, the repeated significance two-sample test is no longer a Brownian motion process

## The CHW process tries to re-establish the Brownian property 

## The CHW process: definition

>> What is the property of Brownian process?
